typography_spectrum: 0.17394269909709692
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.12012140196748078
  lightness: 0.7607437195256352
  saturation: 0.21469037025235593
  rhythmicContrast: 0.8158347341232002
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2661162503063679
analytics:
  google: null
  facebook: null
  twitter: null
name: Bibiano
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 'http://bibiano.io/'
    url: 'http://bibiano.io/'
    name: About
    type: external
  - id: 'https://twitter.com/bibianowency'
    url: 'https://twitter.com/bibianowency'
    name: '@bibianowency'
    type: external
favicon: null
title: Bibiano
purpose: []
