name: Bibiano Wenceslao
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/85d87c38-85ba-40c4-a58b-dee1161de371.png
layout_spectrum: 0
typography_spectrum: 0.43961
author:
  name: Bibiano Wenceslao
  email: me@bibiano.io
  url: 'http://bibiano.io/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8775aaf9-94d3-4a59-8bf0-3839857bae3b.png
navigation:
  - url: 'http://bibiano.io/'
    name: About
    type: external
  - url: 'https://twitter.com/bibianowency'
    name: '@bibianowency'
    type: external
title: 'UX, Social Media, HTML-CSS, Support Hero'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  brandStrength: 0.48852371727116406
  lightness: 0.9079302239697427
  saturation: 0.08465242525562644
  rhythmicContrast: 0.3180615359451622
purpose: []
