typography_spectrum: 0.44705
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49788
analytics:
  google: null
  facebook: null
  twitter: null
name: Bibiano
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 'http://bibiano.io/'
    url: 'http://bibiano.io/'
    name: About
    type: external
favicon: null
title: Bibiano
purpose: []
