typography_spectrum: 0.17394269909709692
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.12012140196748078
  lightness: 0.7607437195256352
  saturation: 0.21469037025235593
  rhythmicContrast: 0.8158347341232002
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2661162503063679
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Bibiano Wenceslao
  email: me@bibiano.io
  url: 'http://bibiano.io/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8775aaf9-94d3-4a59-8bf0-3839857bae3b.png
name: Bibiano Wenceslao
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 'http://bibiano.io/'
    url: 'http://bibiano.io/'
    name: About
    type: external
  - id: 'https://twitter.com/bibianowency'
    url: 'https://twitter.com/bibianowency'
    name: '@bibianowency'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/85d87c38-85ba-40c4-a58b-dee1161de371.png
title: 'UX, Social Media, HTML-CSS, Support Hero'
purpose: []
